// <auto-generated />
using System;
using DAL.Concreate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220302224521_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EntityLayer.Concreate.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BlogContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EntityLayer.Concreate.Sebze", b =>
                {
                    b.Property<int>("SebzeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SebzeFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SebzeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SebzeId");

                    b.ToTable("Sebzeler");
                });

            modelBuilder.Entity("EntityLayer.Concreate.Yemek", b =>
                {
                    b.Property<int>("YemekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("SebzeId")
                        .HasColumnType("int");

                    b.Property<string>("YemekContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YemekName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YemekId");

                    b.HasIndex("BlogId");

                    b.HasIndex("SebzeId");

                    b.ToTable("Yemekler");
                });

            modelBuilder.Entity("EntityLayer.Concreate.Yemek", b =>
                {
                    b.HasOne("EntityLayer.Concreate.Blog", null)
                        .WithMany("Yemeks")
                        .HasForeignKey("BlogId");

                    b.HasOne("EntityLayer.Concreate.Sebze", "Sebze")
                        .WithMany("Yemeks")
                        .HasForeignKey("SebzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sebze");
                });

            modelBuilder.Entity("EntityLayer.Concreate.Blog", b =>
                {
                    b.Navigation("Yemeks");
                });

            modelBuilder.Entity("EntityLayer.Concreate.Sebze", b =>
                {
                    b.Navigation("Yemeks");
                });
#pragma warning restore 612, 618
        }
    }
}
